# Generated by Django 2.2.6 on 2019-10-08 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/agents')),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('is_AOTM', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('question', models.TextField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('image1', models.ImageField(upload_to='media/apartment1')),
                ('image2', models.ImageField(blank=True, upload_to='media/apartment2')),
                ('image3', models.ImageField(blank=True, upload_to='media/apartment3')),
                ('image4', models.ImageField(blank=True, upload_to='media/apartment4')),
                ('image5', models.ImageField(blank=True, upload_to='media/apartment5')),
                ('description', models.TextField()),
                ('available', models.BooleanField(default=True)),
                ('offer', models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale')], default='sale', max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_recent', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='apartments', to='Apartment.Agent')),
            ],
        ),
    ]
