# Generated by Django 2.2.6 on 2019-10-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apartment', '0003_auto_20191024_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='image',
            field=models.ImageField(upload_to='media/agents'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image1',
            field=models.ImageField(upload_to='media/apartment1'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image2',
            field=models.ImageField(blank=True, upload_to='media/apartment2'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image3',
            field=models.ImageField(blank=True, upload_to='media/apartment3'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image4',
            field=models.ImageField(blank=True, upload_to='media/apartment4'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image5',
            field=models.ImageField(blank=True, upload_to='media/apartment5'),
        ),
    ]
