# Generated by Django 2.2.6 on 2021-01-23 20:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apartment', '0004_auto_20191025_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='user_image'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='user_image'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='user_image'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='user_image'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='user_image'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image5',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='user_image'),
        ),
    ]
